version: '3.4'

services:
  web:
    image: dimpex/wiredworld
    build: .
    command: gunicorn --bind=0.0.0.0:8000 WiredWorldProject.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .production-env
    volumes:
      - /tmp/app-resources/static:/app/static_files
      - /tmp/app-resources/media:/app/media_files
    platform: linux/amd64
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .production-env
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/app-resources/static:/home/app/web/staticfiles
      - /tmp/app-resources/media:/home/app/web/mediafiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro