# Generated by Django 4.2.2 on 2023-07-03 18:37

import WiredWorldProject.cart.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(validators=[WiredWorldProject.cart.validators.quantity_validation]),
        ),
    ]
